#!/usr/bin/env bash
set -euo pipefail

# snapMULTI deploy script
# Bootstraps a fresh Linux machine (Raspberry Pi or x86_64) as a snapMULTI server.
# Assumes: OS installed, network configured, SSH enabled.
# Usage: sudo ./deploy.sh

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }
step()  { echo -e "\n${CYAN}${BOLD}==> $*${NC}"; }

# --- Must run as root ---
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root (sudo ./deploy.sh)"
    exit 1
fi

# Capture the real user (not root) for PUID/PGID
REAL_USER="${SUDO_USER:-$(whoami)}"
REAL_UID="$(id -u "$REAL_USER")"
REAL_GID="$(id -g "$REAL_USER")"

# --- Step 1: Preflight checks ---
step "Preflight checks"

# OS
if [[ "$(uname -s)" != "Linux" ]]; then
    error "snapMULTI requires Linux (host networking for mDNS). Detected: $(uname -s)"
    exit 1
fi
info "OS: Linux"

# Architecture
ARCH="$(uname -m)"
case "$ARCH" in
    x86_64)  info "Architecture: amd64" ;;
    aarch64) info "Architecture: arm64" ;;
    armv7l)  info "Architecture: armv7 (supported but arm64 recommended)" ;;
    armv6l)  warn "Architecture: armv6 — too weak for server use (Pi Zero v1 / Pi 1)" ;;
    *)       error "Unsupported architecture: $ARCH"; exit 1 ;;
esac

# Network
if curl -sf --max-time 5 https://ghcr.io >/dev/null 2>&1; then
    info "Network: OK (ghcr.io reachable)"
else
    error "Cannot reach ghcr.io — check network connectivity"
    exit 1
fi

# --- Step 2: Install Docker ---
step "Docker"

if command -v docker >/dev/null 2>&1; then
    info "Docker already installed: $(docker --version)"
else
    info "Installing Docker via official convenience script (https://get.docker.com)..."
    info "Review the script before running: curl -fsSL https://get.docker.com"
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sh /tmp/get-docker.sh
    rm -f /tmp/get-docker.sh
    info "Docker installed: $(docker --version)"
fi

# Ensure docker compose is available
if docker compose version >/dev/null 2>&1; then
    info "Docker Compose: $(docker compose version --short)"
else
    error "Docker Compose not found. Install Docker Compose v2."
    exit 1
fi

# Add real user to docker group
if ! id -nG "$REAL_USER" | grep -qw docker; then
    usermod -aG docker "$REAL_USER"
    info "Added $REAL_USER to docker group (re-login to take effect)"
fi

# Enable and start Docker
systemctl enable docker >/dev/null 2>&1 || true
systemctl start docker

# --- Step 3: Project setup ---
step "Project setup"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ -f "$SCRIPT_DIR/docker-compose.yml" ]]; then
    INSTALL_DIR="$SCRIPT_DIR"
    info "Running from repo: $INSTALL_DIR"
else
    INSTALL_DIR="/opt/snapmulti"
    if [[ -d "$INSTALL_DIR/.git" ]]; then
        info "Updating existing install at $INSTALL_DIR"
        git -C "$INSTALL_DIR" pull --ff-only
    else
        info "Cloning snapMULTI to $INSTALL_DIR"
        git clone https://github.com/lollonet/snapMULTI.git "$INSTALL_DIR"
    fi
fi

cd "$INSTALL_DIR"

# --- Step 4: Create directories ---
step "Creating directories"

dirs=(audio data mpd/data mpd/playlists mympd/workdir mympd/cachedir)
for d in "${dirs[@]}"; do
    mkdir -p "$d"
done
chown -R "$REAL_UID:$REAL_GID" audio data mpd mympd
info "Created: ${dirs[*]}"

# --- Step 5: Generate .env ---
step "Environment configuration"

if [[ -f .env ]]; then
    info "Existing .env found — keeping it"
else
    # Auto-detect timezone
    if command -v timedatectl >/dev/null 2>&1; then
        TZ_DETECTED="$(timedatectl show -p Timezone --value 2>/dev/null || echo "Europe/Berlin")"
    elif [[ -f /etc/timezone ]]; then
        TZ_DETECTED="$(cat /etc/timezone)"
    else
        TZ_DETECTED="Europe/Berlin"
    fi

    cat > .env <<EOF
# snapMULTI Environment Configuration
# Generated by deploy.sh on $(date -Iseconds)

# Music library paths (host)
# Update these to point to your music directories
MUSIC_LOSSLESS_PATH=/media/music/Lossless
MUSIC_LOSSY_PATH=/media/music/Lossy

# Timezone
TZ=$TZ_DETECTED

# User/Group for container processes
PUID=$REAL_UID
PGID=$REAL_GID
EOF

    chown "$REAL_UID:$REAL_GID" .env
    info "Generated .env:"
    info "  TZ=$TZ_DETECTED"
    info "  PUID=$REAL_UID  PGID=$REAL_GID"
    info "  MUSIC_LOSSLESS_PATH=/media/music/Lossless"
    info "  MUSIC_LOSSY_PATH=/media/music/Lossy"
    warn "Edit .env to set your actual music paths if different"
fi

# --- Step 6: Pull images ---
step "Pulling Docker images"

docker compose pull

# --- Step 7: Start services ---
step "Starting services"

docker compose up -d

# --- Step 8: Verify ---
step "Verifying"

sleep 5
RUNNING="$(docker compose ps --format '{{.Name}} {{.Status}}' | grep -c 'Up' || true)"
EXPECTED=5

if [[ "$RUNNING" -ge "$EXPECTED" ]]; then
    info "All $EXPECTED services running"
else
    warn "Only $RUNNING/$EXPECTED services running:"
    docker compose ps
fi

# --- Step 9: Summary ---
IP="$(hostname -I | awk '{print $1}')"

echo ""
echo -e "${GREEN}${BOLD}"
echo "  ========================================"
echo "    snapMULTI is running!"
echo "  ========================================"
echo ""
echo "    myMPD Web UI:  http://${IP}:8180"
echo "    Snapcast API:  http://${IP}:1780"
echo "    MPD Control:   ${IP}:6600"
echo ""
echo "    Connect clients:"
echo "      sudo apt install snapclient"
echo "      snapclient --host ${IP}"
echo ""
echo "    Install dir:   ${INSTALL_DIR}"
echo "    Config:        ${INSTALL_DIR}/.env"
echo "  ========================================"
echo -e "${NC}"
