#!/usr/bin/env bash
# Sourced as a data library; `set -euo pipefail` intentionally omitted.
# shellcheck disable=SC2034
# (Every SYSTEMD_UNITS_* array below is referenced by sourced consumers:
# tests/test_systemd_units.sh today, and firstboot.sh + setup.sh after
# the PR8 helper-migration. Cross-file usage is invisible to shellcheck
# so it would warn on every array; one global disable covers all of
# them.)
#
# systemd-units.sh — SSOT for the systemd units snapMULTI installs
# from packaged static files (i.e. units that exist as .service /
# .timer / .path files in the repo and are copied verbatim to
# /etc/systemd/system/ at firstboot / setup time).
#
# Why this exists (v0.8 hardening track, PR7 — mirrors PR4):
#   The static-unit install pattern repeats N times in firstboot.sh
#   and setup.sh:
#
#     install -m 0644 "$DIR/snapmulti-X.service" /etc/systemd/system/
#     install -m 0644 "$DIR/snapmulti-X.timer"   /etc/systemd/system/
#     systemctl daemon-reload
#     systemctl enable snapmulti-X.timer
#
#   Three drift classes are possible:
#     1. A new .service / .timer / .path file lands in scripts/common/
#        without a matching `install -m 0644` in firstboot.sh → the unit
#        ships on the SD card but never reaches /etc/systemd/system/.
#     2. The install line typos the file name or references a unit not
#        in the repo → the install line silently no-ops or aborts.
#     3. A unit name is renamed in one place but not the other.
#
# This manifest is the declarative source of "what static unit
# bases the project ships". A unit `base` covers EVERY file matching
# `$base.{service,timer,path}` in the unit dir; the helper to enumerate
# extensions lives in PR8 and stays out of this manifest.
#
# The companion test (`tests/test_systemd_units.sh`) asserts:
#   1. Every base in the manifest has at least one matching file under
#      the expected unit dir (server units: `scripts/common/`, client
#      units: `client/common/systemd/`). Catches drift class 2.
#   2. Every `install -m 0644 ... .service|.timer|.path` line in
#      `firstboot.sh` / `setup.sh` references a base that is declared
#      in the matching manifest. Catches drift class 3.
#   3. Every `scripts/common/snapmulti-*.{service,timer,path}` file is
#      declared (under the base name) in `SYSTEMD_UNITS_SERVER`. Catches
#      drift class 1 — the snapmulti-status / mpd-update class regression
#      where a unit shipped but was never enabled.
#
# This PR is PURE-ADDITIVE: firstboot.sh and setup.sh are NOT refactored
# to read from the manifest yet. PR8 will introduce the
# `install_systemd_units BASE SRC_DIR` helper and migrate the inline
# blocks. The value here is the contract — the tests catch drift today,
# before the refactor.
#
# Out of scope (kept as runtime-generated units, NOT in the manifest):
#   - snapclient.service       — generated by setup.sh via a heredoc
#     into /etc/systemd/system/ with per-device parameters.
#   - snapclient-discover.timer / .service — generated by setup.sh from
#     the discover-server.sh / hostname template.
#   - snapmulti-server.service — generated by deploy.sh / setup.sh via
#     systemd-snippets.sh from compose-up logic.
#   These three units exist conceptually in setup.sh + deploy.sh but
#   have no static file in the repo; they are NOT part of the contract
#   this manifest enforces.

# ─── Server bundle ─────────────────────────────────────────────────
# Each entry is a unit BASE name. The matching files are enumerated by
# the helper as `$base.{service,timer,path}` — present extensions are
# installed, missing extensions are silently skipped. The unit dir for
# server bases is `scripts/common/`.
SYSTEMD_UNITS_SERVER=(
    "snapmulti-diagnostics"       # service + timer  — periodic diag bundle
    "snapmulti-backup"            # service + timer  — mpd.db backup
    "snapmulti-mpd-update"        # service + timer  — nightly NFS rescan
    "snapmulti-state-backup"      # service + path + timer — myMPD/snapserver state
    "snapmulti-status"            # service + timer  — /status JSON snapshot
    "snapmulti-wifi-watchdog"     # service          — WiFi reboot loop guard
    "snapmulti-music-bind"        # service          — fstab→bind mount for music
)
SYSTEMD_UNITS_SERVER_DIR="scripts/common"

# ─── Client bundle ─────────────────────────────────────────────────
# Client unit dir is `client/common/systemd/`.
SYSTEMD_UNITS_CLIENT=(
    "snapclient-display"          # service — HDMI fb-display visualizer
)
SYSTEMD_UNITS_CLIENT_DIR="client/common/systemd"
